apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  namespace: poojitha
  labels:
    app: swiggy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
      - name: swiggy-app
        image: iampooji/swiggy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
